src/Entity/Generator.php
<?php

namespace App\Entity;

use App\Repository\GeneratorRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GeneratorRepository::class)]
class Generator
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 255)]
    private $name;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
}

src/Entity/GeneratorStats.php
<?php

namespace App\Entity;

use App\Repository\GeneratorStatsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: GeneratorStatsRepository::class)]
class GeneratorStats
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'integer')]
    private $generator_id;

    #[ORM\Column(type: 'float')]
    private $average_power;

    #[ORM\Column(type: 'integer')]
    private $hour;

    #[ORM\Column(type: 'date')]
    private $date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGeneratorId(): ?int
    {
        return $this->generator_id;
    }

    public function setGeneratorId(?int $generator_id): self
    {
        $this->generator_id = $generator_id;

        return $this;
    }

    public function getAveragePower(): ?float
    {
        return $this->average_power;
    }

    public function setAveragePower(float $average_power): self
    {
        $this->average_power = $average_power;

        return $this;
    }

    public function getHour(): ?int
    {
        return $this->hour;
    }

    public function setHour(int $hour): self
    {
        $this->hour = $hour;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDateAsString(): string {
        return $this->date->format("Y-m-d");
    }
}

src/Form/SearchType.php
<?php

namespace App\Form;

use App\Entity\Generator;
use App\Repository\GeneratorRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\SubmitButton;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class SearchType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('generator', EntityType::class, [
                'class' => Generator::class,
                'query_builder' => function (GeneratorRepository $gr) {
                    return $gr->createQueryBuilder('gr')
                        ->orderBy('gr.id', 'ASC');
                },
                'choice_label' => 'name'
            ])
            ->add('from', DateType::class, [
                'widget' => 'choice',
                'input'  => 'datetime'
            ])
            ->add('to', DateType::class, [
                'widget' => 'choice',
                'input'  => 'datetime'
            ])
            ->add('submit', SubmitType::class, [
                'attr' => ['class' => 'save'],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/GeneratorStatsRedisController.php
<?php

namespace App\Controller;

use App\Message\AddGeneratorCurrentStatsToRedis;
use App\Message\CollectHourlyDataFromRedis;
use App\Repository\GeneratorRepository;
use App\Repository\GeneratorStatsRepository;
use App\Service\RandomFloatNumberGeneratorService;
use App\Service\ValidateDateService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Cache\Adapter\RedisAdapter;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;

class GeneratorStatsRedisController extends AbstractController
{
    #[Route('/generator/stats/redis', name: 'app_generator_stats_redis')]
    public function make_measurement(
        MessageBusInterface $messageBus,
        GeneratorRepository $generatorRepository,
        RandomFloatNumberGeneratorService $randomFloatNumberGeneratorService
    ): Void
    {
        $generator = $generatorRepository->findAll();
        while(True) {
            for($j = 0; $j < 2; $j++) {
                for ($i = 0; $i < count($generator); $i++) {
                    $message = new AddGeneratorCurrentStatsToRedis($generator[$i], $randomFloatNumberGeneratorService->getRandomFloatNumber());
                    $messageBus->dispatch($message);
                }
                usleep(500000);
            }
        }
    }
}

src/Controller/SearchController.php
<?php

namespace App\Controller;

use App\Form\SearchType;
use App\Repository\GeneratorStatsRepository;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Pagerfanta\View\TwitterBootstrap5View;
use Pagerfanta\View\OptionableView;

class SearchController extends AbstractController
{
    #[Route('/', name: 'app_search')]
    public function search(
        Request $request,
        GeneratorStatsRepository $generatorStatsRepository
    ): Response
    {
        $form = $this->createForm(SearchType::class);
        $form->handleRequest($request);
        $queryBuilder = Null;

        if($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $data['from'] = $data['from']->format('Y-m-d');
            $data['to'] = $data['to']->format('Y-m-d');

            return $this->redirectToRoute('app_get_statistics', ["id" => $data['generator']->getId(), "from" => $data['from'], "to" => $data['to']]);
        }

        return $this->render('search.html.twig', [
            'searchForm' => $form->createView()
        ]);
    }

    #[Route('/statistics/{id}/{from}/{to}', name: 'app_get_statistics')]
    public function get_statistics(
        int $id,
        string $from,
        string $to,
        Request $request,
        GeneratorStatsRepository $generatorStatsRepository
    )
    {
        $queryBuilder = $generatorStatsRepository->getGeneratorStatsInDatePeriodQueryBuilder(
            $id,
            $from,
            $to
        );

        $pagerfanta = new Pagerfanta(
            new QueryAdapter($queryBuilder)
        );
        $pagerfanta->setMaxPerPage(96);
        $pagerfanta->setCurrentPage($request->query->get('page', 1));

        return $this->render('get_statistics.html.twig', [
            'pager' => $pagerfanta
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/get_statistics.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<div style="padding: 10px">
    <table style="border: 1px solid; border-collapse: collapse; text-align: center;margin-left:auto;margin-right:auto">
        <tr style="border: 1px solid;">
            <th style="border: 1px solid; padding: 5px;">GeneratorId</th>
            <th style="border: 1px solid; padding: 5px;">Name</th>
            <th style="border: 1px solid; padding: 5px;">Average Power [kW]</th>
            <th style="border: 1px solid; padding: 5px;">Hour</th>
            <th style="border: 1px solid; padding: 5px;">Date</th>
        </tr>
        {% for statistic in pager %}

            <tr style="border: 1px solid;">
                <td style="border: 1px solid; padding: 5px;">{{ statistic[0].getGeneratorId() }}</td>
                <td style="border: 1px solid; padding: 5px;">{{ statistic.name }}</td>
                <td style="border: 1px solid; padding: 5px;">{{ statistic[0].averagePower }}</td>
                <td style="border: 1px solid; padding: 5px;">{{ statistic[0].hour }}</td>
                <td style="border: 1px solid; padding: 5px;">{{ statistic[0].getDateAsString() }}</td>
            </tr>
        {% endfor %}
        {% if pager %}
            <div style="text-align: center; ">
                <a href="{{ url('app_search') }}"><button>Search</button></a>
            </div>
            <div style="text-align: center; padding: 20px">
                {{ pagerfanta(pager) }}
            </div>
        {% endif %}
    </table>
</div>


</body>
</html>

templates/search.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div style="text-align: center">
    <div style="margin-top: 30px">
    {{ form_start(searchForm) }}
        <div>{{ form_widget(searchForm.generator) }}</div><br>
        <div>From: {{ form_widget(searchForm.from) }}</div><br>
        <div>To: {{ form_widget(searchForm.to) }}</div><br>
        {{ form_widget(searchForm.submit) }}
    {{ form_end(searchForm) }}
    </div>
</div>
</body>
</html>